# -*- coding: utf-8 -*-
"""2021_07_16_Yogya_Gupta

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZzxKbplL56eFxuLjs5WAkvYNDahxIzHl

# Project 11: Video Game Sales Analysis - Grouping & Aggregation

### Context

Video games creation is essentially a software development process.  A group of individuals or a company create a video game with the aim of massive profits. Generally, publishers such as EA Sports, Atari, Rockstar Games etc. fund the game development process. However, for publishers, it is very important to estimate the cost of development of a video game. Additionally, they also have to allocate the right amount of budget. If the budget is too little, the quality of a game will get compromised whereas if the budget is too much, their profit margin will reduce. Most of the commercial games do not generate adequate profit. 

A video game is an interactive visual story. A new game must provide novelty and must be a product of innovation. Otherwise, it may turn out repetitive and boring. Many individual groups of game developers shut down their development process and exit the market because they cannot find a publisher or they can't fund the development by themselves as the initial capital investment requirement is humongous. Nevertheless, once the companies become financially stable by making sufficient profits, they may expand to develop newer games or sequels to the initial ones such as FIFA, Call of Duty, Age of Empires etc.

An average development budget for a multiplatform (PC, PS, Xbox etc.) game is US \$18 to 28 million, with high-profile games often exceeding US $40 million.

---

### Problem Statement

Imagine that you work for one of the world's biggest tech giants as a data analyst. The company intends to venture into the video game development business by either creating their own video games and gaming platforms or by funding a group of individual game developers.

As a part of market research, your CEO wants to come up with a business strategy to enable your company to enter into the video game development business. However, in the best interest of companies financial investment in this project, it is important to know whether there are enough buyers, in the long run, do the number of buyers increase so that they stay invested in this project.

Your CEO would like to know what kind of games are most popular in terms of the most units sold, what are the most commonly used gaming platforms such as PS4, Xbox, PC etc.

---

#### Getting Started

Follow the steps described below to solve the project:

1. Click on the link provided below to open the Colab file for this project.
   
   https://colab.research.google.com/drive/1nXtn3CB3jwX8TiBuAPLLU9JiuM3X_w8z?usp=sharing

2. Create the duplicate copy of the Colab file. Here are the steps to create the duplicate copy:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/0_file_menu.png' width=500>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/1_create_colab_duplicate_copy.png' width=500>

     - After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_CapstoneProject11** format. 

3. Now, write your code in the prescribed code cells.

### Dataset Description

You are provided with a video games sales dataset. It consists of the following features:

1. `Rank` - Rank based on the number of units sold of a game. The most sold game is ranked 1.

2. `Name` - The name of a video game.

3. `Platform` - The platform (PC, PS4, XBox etc.) for which a game is released.

4. `Year` - The release year of a video game.

5. `Genre` - The genre of a video game.

6. `Publisher` - The publisher of a video game.

7. `NA_Sales` - Approximately, the total number of units sold (in million) of a video game in North America.

8. `EU_Sales` - Approximately, the total number of units sold (in million) of a video game in Europe.

9. `JP_Sales` - Approximately, the total number of units sold (in million) of a video game in Japan.

10. `Other_Sales` - Approximately, the total number of units sold (in million) of a video game in the rest of the world.

11. `Global_Sales` - Approximately, the total number of units sold (in million) of a video game all over the world.

Here's a link to the dataset:

https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/video-games-sales/video-game-sales.csv

---

### Things To Do

- The `Year` and `Publisher` columns contain few missing values. Treat them accordingly.

- Convert the values contained in the `Year` column into integer values.

- Find out:

  1. The trend of growth in the number of total units sold across the given regions and the world. Also create year-wise line plots for the total number of units sold across different regions and the world.
  
  2. Top 10 most sold genres of video games but at least 100 million units sold globally. Also create genre-wise line plots for the total number of units sold across different regions and the world.

  3. Top 10 best publishers of video games but at least 100 million units sold globally. 
  
  4. Top 10 most commonly used gaming platform but at least 100 million units sold globally.

---

#### 1. Import Modules & Load Data
"""

# Import the modules required.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the dataset.
df_data = pd.read_csv("https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/video-games-sales/video-game-sales.csv")

# Get the dataset information.
df_data.info()

"""---

#### 2. Treat Null Values
"""

# Check for the null values in all the columns.
df_data.isnull().sum()

# Remove the rows/columns containing the null values.
df_data=df_data[df_data["Year"].isna()==False]
df_data=df_data[df_data["Publisher"].isna()==False]
df_data.isnull().sum()

# Convert the data-type of the year values into integer values.
df_data["Year"]=df_data["Year"].astype("int")
df_data["Year"].dtype

"""---

#### 3. Yearly Total Units Sold
"""

# Find out the total number of units sold yearly across different regions and the world
group_by_year=df_data.groupby(by="Year")
func_dict_of_aggr={col:"sum" for col in df_data.columns[6:11]}
yearly_sale=group_by_year.agg(func=func_dict_of_aggr)
yearly_sale

# Create the line plots for the total number of units sold yearly across different regions and the world.
for i in yearly_sale.columns:
  plt.figure(figsize=(9,9))
  plt.plot(yearly_sale.index,yearly_sale[i])
  plt.show()

"""**Q:** In which year, the most number of games were sold globally and how many?

**A:** In 2008 the most number of games were sold globally appr. 678.90
"""

# In which year, the most number of games were sold globally and how many?
yearly_sale[yearly_sale["Global_Sales"]==yearly_sale["Global_Sales"].max()]

"""---

#### 4. Genre-wise Total Units Sold
"""

# Find out the genre-wise total number of units sold across different regions and the world.
genre_group=df_data.groupby(by="Genre")
yearly_genre_sale = genre_group.agg(func=func_dict_of_aggr)
yearly_genre_sale

# Create line plots for genre-wise total number of units sold across different regions and the world.
for j in yearly_genre_sale.columns:
  plt.figure(figsize=(10,5))
  plt.plot(yearly_genre_sale.index,yearly_genre_sale[j])
  plt.show()

"""**Q:** What genre of video game is most popular in Japan in terms of the total number of units sold? Also, provide the total number of units sold in Japan for that genre.

**A:** Role-Playing genre is most popular in Japan .
The total number of units sold in Japan is 350.29
"""

# What genre of video game is most popular in Japan in terms of the total number of units sold?
yearly_genre_sale[yearly_genre_sale['JP_Sales']==yearly_genre_sale['JP_Sales'].max()]

# Genre-wise total number of units sold across different regions and the world in descending order.
genre_group = df_data.groupby(by='Genre')
yearly_genre_sale = genre_group.agg(func=func_dict_of_aggr).sort_values(by='Global_Sales', ascending=False)
yearly_genre_sale.head(10)

"""**Q:** Which genre of the video games sells the most globally and how much?

**A:** Action Games genre have the maximum sale arround 1722 million

---

#### 5. Publisher-wise Total Units Sold
"""

# Find out the publisher-wise total number of units sold across different regions and the world in the descending order.
publisher=df_data.groupby(by='Publisher')
publisher_sale=publisher.agg(func=func_dict_of_aggr).sort_values(by='Global_Sales',ascending=False)
publisher_sale.head(10)

"""**Q:** Which video game publisher sells the most number of units globally and how much?

**A:** Nintendo Publisher sells the most number of units globally approx 1784 million

---

#### 6. Platform-wise Total Units Sold
"""

# Find out the platform-wise the total number of units sold across different regions and the world in the descending order.
platform=df_data.groupby(by='Platform')
platform_sale=platform.agg(func=func_dict_of_aggr).sort_values(by='Global_Sales', ascending=False)
platform_sale.head(10)

"""**Q:** For which platform of a video game, the most number of units are sold globally and how much?

**A:** For PS2 the most number of units of video games are sold arround 1233 million

---

### Submitting the Project

Follow the steps described below to submit the project.

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>


3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_CapstoneProject11**) of the notebook will get copied 

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_CapstoneProject11** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""